# Generated by Django 3.1.7 on 2021-03-26 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210326_0832'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalog',
            name='min_price',
        ),
        migrations.AddField(
            model_name='catalog',
            name='max_price',
            field=models.CharField(blank=True, max_length=20, verbose_name='Цена за комплект (необязательно)'),
        ),
    ]
