# Generated by Django 3.1.7 on 2021-03-22 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210322_0316'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalog',
            name='second_image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='доп фото'),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='Основное фото'),
        ),
    ]
