# Generated by Django 3.2.3 on 2021-06-03 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210326_0941'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateTimeField(auto_now_add=True, verbose_name='Дата заказа')),
                ('first_name', models.CharField(max_length=30, verbose_name='Имя')),
                ('Middle_name', models.CharField(max_length=30, verbose_name='Отчество')),
                ('Phone', models.CharField(max_length=15, verbose_name='Номер телефона')),
                ('Address', models.TextField(verbose_name='Адрес')),
                ('Cart', models.TextField(verbose_name='Корзина')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
        migrations.AlterModelOptions(
            name='furnite_category',
            options={'verbose_name': 'Категория фурнитуры', 'verbose_name_plural': 'Категории фурнитуры'},
        ),
        migrations.AlterModelOptions(
            name='furnite_sub_category',
            options={'verbose_name': 'Подкатегория фурнитуры', 'verbose_name_plural': 'Подкатегории фурнитуры'},
        ),
    ]
