# Generated by Django 3.2.3 on 2021-06-03 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210603_0554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='Date',
            field=models.DateField(auto_now_add=True, verbose_name='Дата заказа'),
        ),
    ]
