# Generated by Django 3.2.3 on 2021-06-03 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_orders_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='Date',
            field=models.DateField(auto_now=True),
        ),
    ]
