# Generated by Django 3.1.7 on 2021-03-22 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210322_0519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='second_image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='доп фото'),
        ),
    ]
