# Generated by Django 3.1.7 on 2021-03-22 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20210322_0520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='second_image',
            field=models.ImageField(blank=True, upload_to='', verbose_name='доп фото'),
        ),
    ]
