# Generated by Django 3.1.7 on 2021-03-22 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20210322_0533'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalog',
            name='discond',
            field=models.CharField(blank=True, max_length=20, verbose_name='Цена со скидкой (необязательно)'),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='second_image',
            field=models.ImageField(blank=True, upload_to='', verbose_name='доп фото (необязательно)'),
        ),
    ]
