# Generated by Django 3.2.3 on 2021-06-03 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_orders_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='Date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата'),
        ),
    ]
