# Generated by Django 3.1.7 on 2021-03-23 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20210323_2346'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalog',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.collection', verbose_name='Коллекция'),
        ),
    ]
